export interface DossierAnalysis {
  attore: string | null;
  convenuto: string | null;
  avvocato_attore: string | null;
  avvocato_convenuto: string | null;
  giudice: string | null;
  indirizzo: string | null;
  foro_competente: string | null;
  sezione_tribunale: string | null;
  totale_richiesto: string | null;
  domanda_riconvenzionale: string | null;
  esito: string | null;
  motivazione: string | null;
  punti_forza_attore: string | null;
  punti_debolezza_attore: string | null;
  punti_forza_convenuto: string | null;
  punti_debolezza_convenuto: string | null;
  sintesi_strategica: string | null;
}
